Mis_Perris/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls import url
from django.contrib.auth import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from MascotasApi import views

router = routers.DefaultRouter()
router.register(r'mascota_api', views.MascotaViewSet)
router.register(r'estado_api', views.EstadoViewSet)

urlpatterns = [
    path('', include('PaginaPrincipal.urls'), name='index'),
    path('', include('pwa.urls')),
    path('mascotas/', include('Mascotas.urls')),
    path('usuario/', include('Usuario.urls')),
    path('admin/', admin.site.urls),       
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(
        r'^password/recovery/$',
        auth_views.PasswordResetView.as_view(
            template_name='auth/password_reset_form.html',
            email_template_name='auth/password_reset_email.html',
        ),
        name='password_reset',
    ),

    url(
        r'^password/recovery/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='auth/password_reset_done.html',
        ),
        name='password_reset_done',
    ),

    url(
        r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('index'),
            post_reset_login=True,
            template_name='auth/password_reset_confirm.html',
            post_reset_login_backend=(
                'django.contrib.auth.backends.AllowAllUsersModelBackend'
            ),
        ),
        name='password_reset_confirm',
    ),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Usuario/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from Mis_Perris import urls

app_name = 'Usuario'
urlpatterns = [
    # ex: /usuarios/
    path('', views.registrar_usuario, name='registrar_usuario'),
    #ex: /usuarios/5
    path('listar_usuarios/', views.listar_usuarios, name="listar_usuarios"),
    path('ajax/cargar_ciudades/', views.cargar_ciudades, name="cargar_ciudades"),    
    path('mi_cuenta/', views.mi_cuenta, name= 'mi_cuenta'),
]

Usuario/models.py
from django.db import models
from django.dispatch import receiver
from allauth.account.signals import user_signed_up

# Create your models here.

class Tipo_Vivienda(models.Model):
    descripcion = models.CharField(max_length=30)

    def __str__(self):
        return self.descripcion

class Region(models.Model):
    numero_region = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return "Region " + str(self.numero_region) + ": " + self.descripcion

class Ciudad(models.Model):
    numero_ciudad = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=50)
    numero_region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.descripcion

class Usuario(models.Model):
    correo_electronico = models.EmailField(max_length=30)
    rut = models.SlugField(primary_key=True, max_length=10)    
    password = models.CharField(max_length=30)
    password_verification = models.CharField(max_length=30)
    nombre_completo = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    telefono = models.IntegerField()
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    tipo_vivienda = models.ForeignKey(Tipo_Vivienda, on_delete=models.CASCADE)

    def __str__(self):
        return self.rut + " - " + self.nombre_completo

@receiver(user_signed_up)
def create_user_profile(request, user, **kwargs):
    profile = Profile.objects.create(user=user)
    profile.save()

Usuario/forms.py
from django.utils.translation import ugettext_lazy as _
from django import forms
from .models import Usuario, Tipo_Vivienda, Region, Ciudad


class UsuarioForm(forms.ModelForm):  
    correo_electronico = forms.EmailField(error_messages={'required': 'El correo electrónico es obligatorio'})   
    rut = forms.SlugField(error_messages={'required': 'El rut es obligatorio'})    
    password = forms.CharField(error_messages={'required': 'El password es obligatorio'})
    password_verification = forms.CharField(error_messages={'required': 'La verificación de password es obligatoria'})
    nombre_completo = forms.CharField(error_messages={'required': 'El nombre completo es obligatorio'})
    fecha_nacimiento = forms.DateField(error_messages={'required': 'La fecha de nacimiento es obligatoria'})
    telefono = forms.IntegerField(error_messages={'required': 'El teléfono es obligatorio'})
    region = forms.ModelChoiceField(queryset=Region.objects.all(), error_messages={'required': 'La región es obligatoria'})
    ciudad = forms.ModelChoiceField(queryset=Ciudad.objects.all(), error_messages={'required': 'La ciudad es obligatoria'})
    tipo_vivienda = forms.ModelChoiceField(queryset=Tipo_Vivienda.objects.all(), error_messages={'required': 'El tipo de vivienda es obligatorio'})
    class Meta:
        model = Usuario
        widgets = {
            'password': forms.PasswordInput(attrs={'readonly': 'readonly'}),
            'password_verification': forms.PasswordInput(attrs={'readonly': 'readonly'})
        }
        fields = '__all__'
                       

class UsuarioLoginForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ('rut', 'password')
        widgets = {
            'rut': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'})
        }
        labels = {
            'rut': _('RUT'),
            'password': _('Contraseña')
        }
      

Usuario/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required

from .forms import UsuarioForm, UsuarioLoginForm
from .models import Usuario, Tipo_Vivienda, Region, Ciudad
from Mascotas.models import Mascota


# Create your views here.
def registrar_usuario(request):
    # Pantalla registro usuario.

    # Recuperar todos los tipos de vivienda.
    tipo_vivienda = Tipo_Vivienda.objects.all()
    # Recuperar las regiones.
    region = Region.objects.all()
    # Recuperar las ciudades, luego se cargan en base a selección
    # de Región.
    ciudad = Ciudad.objects.all()
    # Creación context, valores que se pasarán al template en caso
    # de no ser un request.POST
    context = {
        'tipos_viviendas': tipo_vivienda,
        'regiones': region,
        'ciudades': ciudad,        
    }
    if request.method == "POST":
        form = UsuarioForm(request.POST)       
        if form.is_valid():
            # Se limpia la información recuperada desde el formulario.            
            username = form.cleaned_data['rut']
            email = form.cleaned_data['correo_electronico']
            passwd = form.cleaned_data['password']
            # Se crea una instancia nueva del tipo User.
            # Esta permitirá login y manejo de cuentas. 
            user = User.objects.create_user(username, email, passwd)
            user.save()
            form.save()
            return HttpResponseRedirect('/')
        else:
            print(form)
            context = {
                'tipos_viviendas': tipo_vivienda,
                'regiones': region,
                'ciudades': ciudad,
                'form': form
            }
            # Si el formulario no es válido se redirecciona al mismo
            # form (registrar_usuario)
            return render(request, 'Usuario/registrar_usuario.html', context)
    else:
        return render(request, 'Usuario/registrar_usuario.html', context)
    
@login_required
def listar_usuarios(request):
    # Pantalla lista usuarios    

    # Se recuperan todos los usuarios de las base de datos.
    usuarios = Usuario.objects.all()
    # Creación context, valores que se pasarán al template.
    context = { 'usuarios': usuarios }
    return render(request, 'Usuario/listar_usuarios.html', context)

@login_required
def mi_cuenta(request):
    usuarios = Usuario.objects.get(rut=request.user)
    mascota = Mascota.objects.filter(usuario=usuarios)
    context = {
        'usuarios' : usuarios,
        'mascota' : mascota
    }
    return render(request, 'Usuario/mi_cuenta.html', context)


def cargar_ciudades(request):
    # Carga de ciudades según región seleccionada.
    region_id = request.GET.get('region_id')
    ciudades = Ciudad.objects.filter(numero_region=region_id)
    return render(request, 'Usuario/cargar_ciudades.html', {'ciudades': ciudades})

Usuario/templates/Usuario/cargar_ciudades.html
<option selected disabled>Selecciona una ciudad</option>
{% for ciudad in ciudades %}
<option value="{{ ciudad.numero_ciudad}}"> {{ciudad.descripcion}}</option>
{% endfor %}

Usuario/templates/Usuario/listar_usuarios.html
{% include 'PaginaPrincipal/base.html' %}
  {% block content %}
  {% load static %}
  <style>
    .container{
      margin-top: 100px !important; 
    }

    h1{
      margin-bottom: 5%;
    }
  </style>
    <div class="container">
      <h1 class="text-center">Usuarios registrados</h1>
        <table class="table">
            <thead>
              <tr>                
                <th scope="col">Rut</th>
                <th scope="col">Nombre Completo</th>
                <th scope="col">Correo</th>
                <th scope="col">Telefono</th>
              </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
              <tr>                
                <td>{{usuario.rut}}</td>
                <td>{{usuario.nombre_completo}}</td>
                <td>{{usuario.correo_electronico}}</td>
                <td>{{usuario.telefono}}</td>
              </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>    
{% endblock %}

Usuario/templates/Usuario/mi_cuenta.html
{%include 'PaginaPrincipal/base.html'%}

{%block content%}

{%load static%}

<div class="container">
    <div class="row">
        

        <div id="mis_mascotas" class="container col-md-6">

            <h1 class="text-center">Mis mascotas</h1>

            <table class="table table-bordered table-sm ">

                <thead>

                    <tr class="table-success">

                        <th scope="col">Nombre</th>

                        <th scope="col">Raza</th>

                        <th scope="col">Descripcion</th>



                    </tr>

                </thead>

                <tbody>

                    {%for mascota in mascota%}



                    <tr>

                        <td>{{mascota.nombre}}</td>

                        <td>{{mascota.raza}}</td>

                        <td>{{mascota.descripcion}}</td>

                    </tr>

                    {%endfor%}

                </tbody>

            </table>

        </div>
        <div id="micuenta" class="container col-md-6">

                <div id="cardd" class="card" style=" width: 22rem; padding: 25px;">
    
                    <h1 class="text-center">Mi cuenta</h1>
    
                    <p>Nombre de Usuario (Rut): {{user.username}}</p>
    
                    <p>Nombre: {{usuarios.nombre}}</p>
    
                    <p>Apellido: {{usuarios.apellido}}</p>
    
                    <p>Email: {{usuarios.correo}}</p>
    
                    <p>Fecha Nacimiento: {{usuarios.fecha}}</p>
    
                    <p>Telefono: {{usuarios.telefono}}</p>
    
                    <p>Ciudad: {{usuarios.ciudad}}</p>
    
                </div>
    
            </div>
    </div>
</div>



{%endblock%}

Usuario/templates/Usuario/registrar_usuario.html
{% include 'PaginaPrincipal/base.html' %}
{% load socialaccount %} 
{% block content %}
{% load static %}
<style>
  #formulario{
    margin-top: 100px;    
  }
  h1{
    margin-bottom: 5%;
  }
</style>
<div class="container">
  <div id="formulario">
    <h1 class="text-center">Registro de Adopción</h1>
    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
    <form method="post" action="{% url 'Usuario:registrar_usuario' %}">
      {% csrf_token %}

      <div id="nombre" class="form-group">
        <label for="nombre">Nombre completo</label>
        <input class="form-control" name="nombre_completo" type="text" placeholder="Ingresa tu nombre completo"
          minlength="3" maxlength="30" pattern="^[a-zA-Z ]+$" required>
      </div>

      <div id="rut" class="form-group">
        <label for="rut">Rut</label>
        <input class="form-control" id="rut" name="rut" type="text" placeholder="12345678-k" minlength="9" maxlength="10"
          pattern="^[0-9Kk-]+$" title="sin puntos con guión" onblur="ValidarRut(this)" required>
      </div>

      <div id="correo" class="form-group">
        <label for="correo_electronico">Correo electrónico</label>
        <input class="form-control" name="correo_electronico" type="email" placeholder="ejemplo@gmail.com" pattern="^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$"
          required>
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" class="form-control" name="password" type="password" required>
      </div>

      <div class="form-group">
        <label for="password_verification">Verificación Password</label>
        <input id="password_verification" class="form-control" name="password_verification" type="password" required
        onchange="VerificarPassword()">
      </div>

      <div id="alert_message" class="alert alert-danger" role="alert" hidden>
          <strong>Atención</strong> los campos Password y Verificación de Password no coinciden
        </div> 

      <div id="fecha" class="form-group">
        <label for="fecha_nacimiento">Fecha Nacimiento</label>
        <input class="form-control" name="fecha_nacimiento" type="date" format="dd/mm/yyyy" required>
      </div>

      <div id="telefono" class="form-group">
        <label for="telefono">Teléfono</label>
        <input class="form-control" name="telefono" type="number" placeholder="Ingresa tu número" minlength="8"
          maxlength="9" pattern="^[0-9]+$" required>
      </div>

      <div id="region" class="form-group">
        <label for="region">Región</label>
        <select class="form-control" id="select_region" name="region" required>
          <option selected disabled>Selecciona una región</option>
          {% for region in regiones %}
          <option value="{{region.numero_region}}">{{region}}</option>
          {% endfor %}
        </select>
      </div>

      <div id="ciudad" class="form-group">
        <label for="ciudad">Ciudad</label>
        <select class="form-control" id="select_ciudad" name="ciudad" required disabled>
          <option selected disabled>Selecciona una ciudad</option>
          {% for ciudad in ciudades %}
          <option value="">{{ciudad}}</option>
          {% endfor %}
        </select>
      </div>

      <div id="tipo_vivienda" class="form-group">
        <label for="tipo_vivienda">Tipo de Vivienda</label>
        <select class="form-control" name="tipo_vivienda" required>
          <option selected disabled>Selecciona una opción</option>
          {% for tipo_vivienda in tipos_viviendas %}
          <option value="{{tipo_vivienda.id}}">{{tipo_vivienda.descripcion}}</option>
          {% endfor %}
        </select>
      </div>
      <input class="btn btn-success" id="registrar" type="submit" value="Registrar">
      <a class="btn btn-primary " style="margin-top:15px;"href="{% provider_login_url 'facebook' method='oauth2' %}">
        <span class="fab fa-facebook"></span>
        Continuar con Facebook
    </a>
      </form>
  </div>
  <script src="{% static 'Usuario/js/form.js' %}"></script>
</div>
{% block javascript%}
<script>
  $("#select_region").change(function () {
    var form = $(this).closest("form");
    var region_id = $(this).val();
    $.ajax({
      url: '{% url "Usuario:cargar_ciudades" %}',
      data: {
        'region_id': region_id
      },
      success: function (data) {
        console.log("Llego")
        $("#select_ciudad").html(data);
        $("#select_ciudad").attr('disabled', false);
      }
    })
  })
</script>
{% endblock %}
{% endblock %}