Mascotas/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='Mascotas'

urlpatterns=[
    # ex: Mascotas
    path('', views.index, name="index"),
    path('registrar/', views.registrar_mascota, name="registrar_mascota"),
    path('listar_mascotas/',  views.listar_mascotas, name="listar_mascotas"),
    path('editar_mascota/<int:id_mascota>', views.editar_mascota, name="editar_mascota"),
    path('borrar_mascota/<int:id_mascota>', views.borrar_mascota, name="borrar_mascota"),
    path('ajax/seleccionar_mascota_estado', views.seleccionar_mascota_estado, name="seleccionar_mascota_estado"),
    path('adoptar/<int:id_mascota>', views.adoptar, name="adoptar")
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mis_Perris/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls import url
from django.contrib.auth import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from MascotasApi import views

router = routers.DefaultRouter()
router.register(r'mascota_api', views.MascotaViewSet)
router.register(r'estado_api', views.EstadoViewSet)

urlpatterns = [
    path('', include('PaginaPrincipal.urls'), name='index'),
    path('', include('pwa.urls')),
    path('mascotas/', include('Mascotas.urls')),
    path('usuario/', include('Usuario.urls')),
    path('admin/', admin.site.urls),       
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(
        r'^password/recovery/$',
        auth_views.PasswordResetView.as_view(
            template_name='auth/password_reset_form.html',
            email_template_name='auth/password_reset_email.html',
        ),
        name='password_reset',
    ),

    url(
        r'^password/recovery/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='auth/password_reset_done.html',
        ),
        name='password_reset_done',
    ),

    url(
        r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('index'),
            post_reset_login=True,
            template_name='auth/password_reset_confirm.html',
            post_reset_login_backend=(
                'django.contrib.auth.backends.AllowAllUsersModelBackend'
            ),
        ),
        name='password_reset_confirm',
    ),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Usuario/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from Mis_Perris import urls

app_name = 'Usuario'
urlpatterns = [
    # ex: /usuarios/
    path('', views.registrar_usuario, name='registrar_usuario'),
    #ex: /usuarios/5
    path('listar_usuarios/', views.listar_usuarios, name="listar_usuarios"),
    path('ajax/cargar_ciudades/', views.cargar_ciudades, name="cargar_ciudades"),    
    path('mi_cuenta/', views.mi_cuenta, name= 'mi_cuenta'),
]

Mascotas/models.py
from django.db import models
from Usuario.models import Usuario

# Create your models here.

class Estado(models.Model):
    descripcion = models.CharField(max_length=30)

    def __str__(self):
        return self.descripcion

class Mascota(models.Model):    
    nombre = models.CharField(max_length=30)
    fotografia = models.ImageField(default='img_folder/None/no-img.jpg')
    raza = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=50)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.nombre

Mascotas/forms.py
from django import forms
from .models import Mascota, Estado

class MascotaForm(forms.ModelForm):
    nombre = forms.CharField(error_messages={'required': 'El nombre de la mascota es obligatorio.'})
    fotografia = forms.ImageField(error_messages={'required': 'La fotografía de la mascota es obligatoria.'})
    raza = forms.CharField(error_messages={'required': 'La raza de la mascota es obligatoria.'})
    descripcion = forms.CharField(error_messages={'required': 'La descripción de la mascota es obligatoria.'})
    estado = forms.ModelChoiceField(queryset=Estado.objects.all(), error_messages={'required': 'El estado de la mascota es obligatorio.'})
    class Meta:
        model = Mascota
        fields = '__all__'
        exclude = ('usuario',)

Mascotas/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Mascota, Estado
from Usuario.models import Usuario
from .forms import MascotaForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    estado = Estado.objects.get(descripcion='Disponible')
    disponibles = Mascota.objects.filter(estado=estado)
    context = {
        'disponibles':disponibles
    }
    return render(request, 'Mascotas/index.html', context)

@login_required
def registrar_mascota(request):
    estados = Estado.objects.all()
    if request.method == 'POST':
        form = MascotaForm(request.POST, request.FILES)
        print(form)
        if form.is_valid():
            print('Todo bien')
            form.save()            
            message = '%s agregada de forma exitosa'%form.cleaned_data['nombre']
            mascotas = Mascota.objects.all()
            estados = Estado.objects.all()
            context = {
                'mascotas': mascotas,
                'estados': estados,
                'message':message
            }
            return render(request, 'Mascotas/lista_perritos.html', context)
        else:
            return render(request, 'Mascotas/registrar_mascotas.html', {'estados': estados})        
    return render(request, 'Mascotas/registrar_mascotas.html', {'estados': estados})

@login_required
def listar_mascotas(request):
    mascotas = Mascota.objects.all()
    estados = Estado.objects.all()
    context = {
        'mascotas': mascotas,
        'estados': estados
    }
    return render(request, 'Mascotas/lista_perritos.html', context)
@login_required
def editar_mascota(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)    
    estados = Estado.objects.all()
    context = {
        'mascota': mascota,
        'estados': estados
    }
    if request.method == 'POST':
        form = MascotaForm(request.POST, request.FILES)        
        if form.is_valid():            
            mascota_form = MascotaForm(request.POST, request.FILES, instance=mascota)
            mascota_form.save(commit=True)
            print("Hola")
            message = '%s editada de forma exitosa'%form.cleaned_data['nombre']
            mascotas = Mascota.objects.all()
            estados = Estado.objects.all()
            context = {
                'mascotas': mascotas,
                'estados': estados,
                'message':message
            }
            return render(request, 'Mascotas/lista_perritos.html', context)
        else:
            return render(request, 'Mascotas/editar_mascota.html', context)
    else:    
        return render(request, 'Mascotas/editar_mascota.html', context)
@login_required
def borrar_mascota(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'POST':
        mascota.fotografia.delete()
        message = '%s borrada de forma exitosa'%mascota.nombre
        mascota.delete()
        
        mascotas = Mascota.objects.all()
        estados = Estado.objects.all()
        context = {
            'mascotas': mascotas,
            'estados': estados,
            'message':message
        }
        return render(request, 'Mascotas/lista_perritos.html', context)
    return render(request, 'Mascotas/borrar_mascota.html', {'mascota':mascota})

def seleccionar_mascota_estado(request):    
    if request.GET.get('estado_id') == str(-1):
        print('llega hasta aca!!!')
        mascotas = Mascota.objects.all()
        estados = Estado.objects.all()
        context = {
            'mascotas': mascotas,
            'estados': estados
        }
        return render(request, 'Mascotas/listar_mascotas_estado.html', context)
    else:
        estado = request.GET.get('estado_id')
        mascotas = Mascota.objects.filter(estado = estado)
        estados = Estado.objects.all()
        context = {
            'mascotas': mascotas,
            'estados': estados
        }
        return render(request, 'Mascotas/listar_mascotas_estado.html', context)

@login_required
def adoptar(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    estado = Estado.objects.get(descripcion='Adoptado')
    usuario = Usuario.objects.get(rut=request.user)
    mascota.estado = estado
    mascota.usuario = usuario
    mascota.save()       
    return HttpResponseRedirect('/')

Mascotas/templates/Mascotas/borrar_mascota.html
{% extends 'PaginaPrincipal/base.html' %}
{% block content%}
<style>
    .container{
        margin-top: 100px;   
    }
</style>
<div class="container">
    <h1 class="text-center">Borrar Mascota</h1>
    <form action="{% url 'Mascotas:borrar_mascota' id_mascota=mascota.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Nombre mascota" value="{{mascota.nombre}}"
                disabled>
        </div>
        <div class="form-group">
            <label for="fotografia">Fotografía</label>
            <img class="img-thumbnail" src="{{mascota.fotografia.url}}" alt="Imagen de perrito {{mascota.nombre}}">
        </div>


        <a class="btn btn-danger" data-toggle="modal" data-target="#modalConfirmacion">Borrar</a>

        <!-- Modal -->
        <div class="modal fade" id="modalConfirmacion" tabindex="-1" role="dialog" aria-labelledby="modalConfirmacionTitulo"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Confirmación adopción</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Confirme si desea borrar a {{mascota.nombre}}</p>
                    </div>
                    <div class="modal-footer">
                        <input class="btn btn-danger" type="submit" value="Borrar">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

Mascotas/templates/Mascotas/editar_mascota.html
{% extends 'PaginaPrincipal/base.html' %}

{% block content%}
<style>
    .container{
        margin-top: 100px;   
    }
</style>
<div class="container">
    <h1 class="text-center">Editar Mascota</h1>
    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
    <form action="{% url 'Mascotas:editar_mascota' id_mascota=mascota.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Nombre mascota" value="{{mascota.nombre}}">
        </div>
        <div class="form-group">
            <label for="raza">Raza predominante</label>
            <input class="form-control" type="text" name="raza" id="raza" placeholder="Raza mascota" value="{{mascota.raza}}">
        </div>
        <div class="form-group">
            <label for="estado">Estado</label>
            <select class="form-control" name="estado" id="estado">
                <option value="" selected disabled>Seleccione un estado</option>
                {% for estado in estados %}
                <option value="{{estado.id}}">{{estado.descripcion}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="fotografia">Fotografía</label>
            <input class="form-control" type="file" name="fotografia" id="fotografia" value="{{mascota.fotografia.url}}">
        </div>
        <div class="form-group">
            <label for="descripcion">Descripción</label>
            <input class="form-control" type="text" name="descripcion" id="descripcion" placeholder="Descripcion mascota" value="{{mascota.descripcion}}">
        </div>
        <input class="btn btn-warning" type="submit" value="Editar">
    </form>    
</div>
{% endblock %}

Mascotas/templates/Mascotas/lista_perritos.html
{% include 'PaginaPrincipal/base.html' %}
{% block content %}
{% load static %}
<style>
  .container {
    margin-top: 100px !important;
  }

  h1 {
    margin-bottom: 5%;
  }

  .img-thumbnail {
    max-width: 25%;
  }
</style>
<div class="container">
    {%if message%}    
    <div id="alert_message" class="alert alert-success" role="alert">
      {{message}}
    </div>   
    <script>
      // Manejo alert
      $("#alert_message").fadeOut(3000, 0). slideUp(2000, function(){
        $(this).remove();
      })
    </script> 
    {% endif %}
  <h1 class="text-center">Perritos registrados</h1>
  {% if mascotas %}
  <form action="POST" novalidate>
    {% csrf_token %}
    <div class="form-group">
      <label for="estado">Seleccione estado</label>
      <select class="form-control" name="estado" id="estado" style="max-width: 300px">
        <option value="" selected disabled>Seleccione estado</option>
        <option value="-1">Todos</option>
        {% for estado in estados %}
        <option value="{{estado.id}}">{{estado.descripcion}}</option>
        {% endfor %}
      </select>
    </div>
  </form>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Raza</th>
        <th scope="col">Estado</th>
        <th scope="col">Foto</th>
        <th scope="col">Editar</th>
        <th scope="col">Borrar</th>
      </tr>
    </thead>
    <tbody id="mascotas_tbody">
      {% for mascota in mascotas %}
      <tr>
        <td>{{mascota.nombre}}</td>
        <td>{{mascota.raza}}</td>
        <td>{{mascota.estado}}</td>
        <td><img class="img-thumbnail" src="{{mascota.fotografia.url}}" alt="Imagen de perrito {{mascota.nombre}}"></td>
        <td><a href="{% url 'Mascotas:editar_mascota' id_mascota=mascota.id %}" class="btn btn-warning">Editar</a></td>
        <td><a href="{% url 'Mascotas:borrar_mascota' id_mascota=mascota.id %}" class="btn btn-danger">Borrar</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <h2 class="text-center">No hay perritos registrados</h2>
  {% endif %}
</div>
<script>
  $("#estado").change(function () {
    var form = $(this).closest("form");
    var estado_id = $(this).val();
    $.ajax({
      url: '{% url "Mascotas:seleccionar_mascota_estado" %}',
      data: {
        'estado_id': estado_id
      },
      success: function (data) {
        $("#mascotas_tbody").html('');        
        $("#mascotas_tbody").html(data);
      }
    })
  })
</script>
{% endblock %}

Mascotas/templates/Mascotas/listar_mascotas_estado.html
{% for mascota in mascotas %}
<tr>
    <td>{{mascota.nombre}}</td>
    <td>{{mascota.raza}}</td>
    <td>{{mascota.estado}}</td>
    <td><img class="img-thumbnail" src="{{mascota.fotografia.url}}" alt="Imagen de perrito {{mascota.nombre}}"></td>
    <td><a href="{% url 'Mascotas:editar_mascota' id_mascota=mascota.id %}" class="btn btn-warning">Editar</a></td>
    <td><a href="{% url 'Mascotas:borrar_mascota' id_mascota=mascota.id %}" class="btn btn-danger">Borrar</a></td>
</tr>
{% endfor %}

Mascotas/templates/Mascotas/registrar_mascotas.html
{% extends 'PaginaPrincipal/base.html' %}

{% block content%}
<style>
    .container{
        margin-top: 100px;   
    }
</style>
<div class="container">
    <h1 class="text-center">Registrar Mascota</h1>
    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
    <form action="{% url 'Mascotas:registrar_mascota' %}" method="post" enctype="multipart/form-data">        
        {% csrf_token%}
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Nombre mascota" required>
        </div>
        <div class="form-group">
            <label for="raza">Raza predominante</label>
            <input class="form-control" type="text" name="raza" id="raza" placeholder="Raza mascota" required>
        </div>
        <div class="form-group">
            <label for="estado">Estado</label>
            <select class="form-control" name="estado" id="estado" required>
                <option value="" selected disabled>Seleccione un estado</option>
                {% for estado in estados %}
                <option value="{{estado.id}}">{{estado.descripcion}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="fotografia">Fotografía</label>
            <input class="form-control" type="file" name="fotografia" id="fotografia" required>
        </div>
        <div class="form-group">
            <label for="descripcion">Descripción</label>
            <input class="form-control" type="text" name="descripcion" id="descripcion" placeholder="Descripcion mascota" required>
        </div>
        <input class="btn btn-success" type="submit" value="Registrar">
    </form>
</div>
{% endblock %}