Mascotas/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='Mascotas'

urlpatterns=[
    # ex: Mascotas
    path('', views.index, name="index"),
    path('registrar/', views.registrar_mascota, name="registrar_mascota"),
    path('listar_mascotas/',  views.listar_mascotas, name="listar_mascotas"),
    path('editar_mascota/<int:id_mascota>', views.editar_mascota, name="editar_mascota"),
    path('borrar_mascota/<int:id_mascota>', views.borrar_mascota, name="borrar_mascota"),
    path('ajax/seleccionar_mascota_estado', views.seleccionar_mascota_estado, name="seleccionar_mascota_estado"),
    path('adoptar/<int:id_mascota>', views.adoptar, name="adoptar")
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mis_Perris/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls import url
from django.contrib.auth import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from MascotasApi import views

router = routers.DefaultRouter()
router.register(r'mascota_api', views.MascotaViewSet)
router.register(r'estado_api', views.EstadoViewSet)

urlpatterns = [
    path('', include('PaginaPrincipal.urls'), name='index'),
    path('', include('pwa.urls')),
    path('mascotas/', include('Mascotas.urls')),
    path('usuario/', include('Usuario.urls')),
    path('admin/', admin.site.urls),       
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(
        r'^password/recovery/$',
        auth_views.PasswordResetView.as_view(
            template_name='auth/password_reset_form.html',
            email_template_name='auth/password_reset_email.html',
        ),
        name='password_reset',
    ),

    url(
        r'^password/recovery/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='auth/password_reset_done.html',
        ),
        name='password_reset_done',
    ),

    url(
        r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('index'),
            post_reset_login=True,
            template_name='auth/password_reset_confirm.html',
            post_reset_login_backend=(
                'django.contrib.auth.backends.AllowAllUsersModelBackend'
            ),
        ),
        name='password_reset_confirm',
    ),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PaginaPrincipal/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='Pagina_Principal'

urlpatterns=[
    # ex: Mascotas
    path('', views.index, name="index"),
    path('base_layout',views.base_layout,name='base_layout'),   
    path('getdata',views.getdata,name='getdata')
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Usuario/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from Mis_Perris import urls

app_name = 'Usuario'
urlpatterns = [
    # ex: /usuarios/
    path('', views.registrar_usuario, name='registrar_usuario'),
    #ex: /usuarios/5
    path('listar_usuarios/', views.listar_usuarios, name="listar_usuarios"),
    path('ajax/cargar_ciudades/', views.cargar_ciudades, name="cargar_ciudades"),    
    path('mi_cuenta/', views.mi_cuenta, name= 'mi_cuenta'),
]

PaginaPrincipal/models.py
from django.db import models

# Create your models here.

PaginaPrincipal/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from Mascotas.models import Estado, Mascota


# Create your views here.
def index(request):
    try:
        estado = Estado.objects.get(descripcion='Disponible')
        disponibles = Mascota.objects.filter(estado=estado)
        context = {
            'disponibles':disponibles
        }    
    except Estado.DoesNotExist:
        context = {}       
        
    return render(request, 'PaginaPrincipal/index.html', context)

def getdata(request):
    try:
        estado = Estado.objects.get(descripcion='Disponible')
        disponibles = Mascota.objects.filter(estado=estado)        
        jsondata = serializers.serialize('json', disponibles)
        return HttpResponse(jsondata)
    except Estado.DoesNotExist:
        return HttpResponse("Error")
    


def base_layout(request):
    template = 'PaginaPrincipal/base.html'
    return render(request, template)

PaginaPrincipal/templates/PaginaPrincipal/base.html
<!DOCTYPE html>
<html lang="en">
{% load pwa %}
{% load static %}

<head>
    {% progressive_web_app_meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{% static '/js/jquery-3.3.1.js' %}"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Teko|Indie+Flower|Advent+Pro" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.2.0/ekko-lightbox.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{%static '/css/estilos.css'%}">
    <link rel="stylesheet" href="{% static '/css/form.css' %}">    
    <title>Mis Perris</title>
</head>

<body>
    <!-- Menu -->
    <nav id="menu" class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="d-flex flex-grow-1">
            <a class="navbar-brand order-0 flex-grow-1" href="{% url 'Pagina_Principal:index' %}"><img id="logo" src="{% static '/img/logo.png' %}"
                    alt="Logo Mis Perris"> </a>
            <span class="flex-grow-1 w-100">
                <!-- Separador --> </span>
            <div class="d-flex flex-grow-1">
                <button id="btn_menu" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMobile"
                    aria-controls="navbarMobile" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
        <div class="collapse navbar-collapse flex-grow-1" id="navbarMobile">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Pagina_Principal:index' %}">Inicio <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Quienes Somos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Servicios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contactenos</a>
                </li>
                {% if request.user.is_superuser %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdownUsuarios" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        Usuarios
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownUsuarios">
                        <a class="dropdown-item" href="{% url 'Usuario:listar_usuarios' %}">Listar</a>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdownMascotas" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        Mascotas
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMascotas">
                        <a class="dropdown-item" href="{% url 'Mascotas:registrar_mascota' %}">Registrar</a>
                        <a class="dropdown-item" href="{% url 'Mascotas:listar_mascotas' %}">Listar</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-user-times" style="font-size: 20px"></i>
                        Logout</a>
                </li>
                {% else %}
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <p>{{ request.user.name }}</p>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#galeria"><i class="fas fa-paw" style="font-size: 20px"></i> Adoptar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Usuario:mi_cuenta' %}">Mi cuenta</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-user-times" style="font-size: 20px"></i>
                        Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Usuario:registrar_usuario' %}"><i class="fas fa-user-plus" style="font-size: 20px"></i>
                        Registrarse</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"><i class="fas fa-user" style="font-size: 20px"></i>
                        Iniciar Sesión</a>
                </li>
                {% endif %}
                {% endif %}

            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}

    <div id="offlineInfo" style="margin-top: 90px;">
        
    </div>
    <script type="text/javascript" src="{% static 'js/idb.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/idbop.js' %}"></script>
</body>

</html>

PaginaPrincipal/templates/PaginaPrincipal/index.html
{% extends 'PaginaPrincipal/base.html' %}

{%block content%}
{%load static%}

<div class="container">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{%static '/img/adoptados/Apolo.jpg'%}" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
          <h4>Apolo</h4>
          <p>Somos muy felices con Apolo.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{%static '/img/adoptados/Duque.jpg'%}" alt="Second slide">
        <div class="carousel-caption d-none d-md-block">
          <h4>Duque</h4>
          <p>Duque es un perrito feliz.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{%static '/img/adoptados/Tom.jpg'%}" alt="Third slide">
        <div class="carousel-caption d-none d-md-block">
          <h4>Tom</h4>
          <p>Queremos conseguirle a Jerry.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>


<div id="social">
  <a><i class="fab fa-facebook-f"></i></a>
  <a><i class="fab fa-google-plus-g"></i></a>
  <a><i class="fab fa-instagram"></i></a>
  <a><i class="fas fa-envelope"></i></a>
</div>
</div>
<div id="etapas">
  <div id="rescate">
    <h2>RESCATE</h2>
    <p>ETAPA UNO</p>
    <hr class="estiloHR">
    <p>Rescatamos perros en situación de peligro y/o abandono. Los rehabilitamos y los preparamos para buscarles un
      hogar.</p>
    <img class="img-etapas" src="{%static '/img/rescate.jpg'%}" alt="Perro">
  </div>
  <div id="crowfunding">
    <img class="img-etapas" src="{%static '/img/crowfunding.jpg'%}" alt="Plato comida perro">
    <h2>CROWFUNDING</h2>
    <p>FINANCIAMIENTO</p>
    <hr class="estiloHR">
    <p>Sigue nuestras redes sociales para informarte acerca de las diversas campañas y actividades que realizamos para
      obtener financiamiento para seguir ayudando.</p>
    <button class="btn_blanco">CAMPAÑAS</button>
  </div>
</div>

<section id="galeria">
  <h2 class="text-center">RESCATADOS</h2>
  <p class="text-center">Esperando ser adoptados.</p>
  <div id="imagenes-galeria" class="container">
    <div id="row" class="row">
      {%if disponibles%}
      {% for disponible in disponibles%}
      <div class="foto col-lg-4 col-md-6">
        <div id="boton" class="row">
          <div class="col-6">
            <a href="{{disponible.fotografia.url}}" data-toggle="lightbox" data-gallery="gallery">
              <img src="{{disponible.fotografia.url}}" class="img-fluid">
            </a>
          </div>
          <div class="col-6">
            <h1 class="text-center">{{disponible.nombre}}</h1>
            <p>{{disponible.descripcion}}</p>
            {%if request.user.is_authenticated%}
            {% if request.user.is_superuser%}
            <a href="{%url 'Mascotas:listar_mascotas' %}" class="btn btn-outline-info">Ver</a>
            {%else%}
            <button class="btn btn-success" data-toggle="modal" data-target="#exampleModalCenter">Adoptar</button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
              aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLongTitle">Confirmación adopción</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <p>Confirme si desea adoptar a {{disponible.nombre}}</p>
                  </div>
                  <div class="modal-footer">
                    <a href="{%url 'Mascotas:adoptar' id_mascota=disponible.id %}" class="btn btn-outline-success">Adoptar</a>
                    <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Cancelar</button>
                  </div>
                </div>
              </div>
            </div>
            {%endif%}
            {%else%}

            <a href="{%url 'Usuario:registrar_usuario' %}" class="btn btn-outline-info">Adoptar</a>

            {%endif%}
          </div>
        </div>
      </div>
      {%endfor%}
      {% else %}

      <h5 class="text-center"> ¡No hay mascotas!</h5>

      {%endif%}

    </div>
  </div>



  <script>
    $(document).on("click", '[data-toggle="lightbox"]', function (event) {
      event.preventDefault();
      $(this).ekkoLightbox();
    });
  </script>

</section>
<footer>
  <p>Desarrollo Web y Mobile. 2018</p>
  <p>Nicole Vera</p>
  <p>Facundo Varas</p>
</footer>


{%endblock%}